version: "3.9"

services:
  db:
    image: postgis/postgis:14-3.2
    volumes:
      - /database-data:/var/lib/postgresql/data/
    env_file:
      - .env.db
#    environment:
#      - POSTGRES_INITDB_ARGS=--locale=en_US.utf8
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==db"