version: "3.9"

services:
  db:
    image: postgis/postgis:14-3.2
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./deploy/postgres:/var/lib/postgres
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==db"
