version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:alpine"

    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

    deploy:
      placement:
        constraints:
          - "node.labels.TAG==prod"

  django:
    image: django-prod
    command: python manage.py runserver 0.0.0.0:8010
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
      - /var/www:/var/www
    ports:
      - target: 8010
        published: 8010
        protocol: tcp
        mode: host
    depends_on:
      - rabbitmq
    restart: on-failure
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==prod"

  celery:
    image: django-prod
    #https://stackoverflow.com/questions/55249197/what-are-the-consequences-of-disabling-gossip-mingle-and-heartbeat-for-celery-w
    command: celery -A open_schools_platform.tasks worker -l info --without-mingle --without-gossip
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
      - /var/www:/var/www
    depends_on:
      - rabbitmq
    restart: on-failure
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==prod"

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - FLOWER_PORT=5555
    ports:
      - target: 5555
        published: 5555
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==prod"

  beats:
    image: django-prod
    command: celery -A open_schools_platform.tasks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
      - /var/www:/var/www
    depends_on:
      - rabbitmq
    restart: on-failure
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==prod"
