name: Django application
on: [push]
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
        echo SMS_API_KEY=${{secrets.SMS_API_KEY}} >> .env
        echo EMAIL_ID=${{ secrets.EMAIL_ID }} >> .env
        echo EMAIL_PRIVATE_API_KEY=${{ secrets.EMAIL_PRIVATE_API_KEY }} >> .env
        echo GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_MAPS_API_KEY}} >> .env
        echo AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY}} >> .env
        echo AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} >> .env
        echo YANDEX_CLIENT_DOCS_BUCKET_NAME=${{secrets.YANDEX_CLIENT_DOCS_BUCKET_NAME}} >> .env
        echo FCM_SERVER_KEY=${{secrets.FCM_SERVER_KEY}} >> .env
        touch firebase_admin_config.json
        echo ${{ secrets.FIREBASE_ADMIN_CONFIG }} >> firebase_admin_config.json
    - name: Build docker
      run: docker-compose build
    - name: Type check
      run: docker-compose run django mypy open_schools_platform/
    - name: Run migrations
      run: docker-compose run django python manage.py migrate
    - name: Run tests
      run: docker-compose run django py.test

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
        echo SMS_API_KEY=${{secrets.SMS_API_KEY}} >> .env
        echo EMAIL_ID=${{ secrets.EMAIL_ID }} >> .env
        echo EMAIL_PRIVATE_API_KEY=${{ secrets.EMAIL_PRIVATE_API_KEY }} >> .env
        echo GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_MAPS_API_KEY}} >> .env
        echo AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY}} >> .env
        echo AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} >> .env
        echo YANDEX_CLIENT_DOCS_BUCKET_NAME=${{secrets.YANDEX_CLIENT_DOCS_BUCKET_NAME}} >> .env
        echo FCM_SERVER_KEY=${{secrets.FCM_SERVER_KEY}} >> .env
        touch firebase_admin_config.json
        echo ${{ secrets.FIREBASE_ADMIN_CONFIG }} >> firebase_admin_config.json
    - name: Fetch history, because Heroku deploy fails otherwise.
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
        sudo apt-get update
        sudo apt-get install binutils libproj-dev gdal-bin
        sudo apt-get install libgeos++
        sudo apt-get install proj-bin
        sudo apt install gdal-bin
    - name: Type check
      run: mypy open_schools_platform/
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: py.test
