name: Django application
on: [push]
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SMS_API_KEY: ${{secrets.SMS_API_KEY}}
    - name: Build docker
      run: docker-compose build
    - name: Type check
      run: docker-compose run django mypy open_schools_platform/
    - name: Run migrations
      run: docker-compose run django python manage.py migrate
    - name: Run tests
      run: docker-compose run django py.test

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SMS_API_KEY: ${{secrets.SMS_API_KEY}}
    - name: Fetch history, because Heroku deploy fails otherwise.
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
    - name: Type check
      run: mypy open_schools_platform/
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: py.test
